---
title: "Info P1 "
output: html_notebook
---

# cargar librerias 
```{r}
library(readr)
library(dplyr)
library (ggplot2)
library(stringr)
library(scales)
library(lubridate)
library(modeest)
```

# Asignamos DF's con los datos RAW de los archivos
```{r}
DFFallecidosRAW <- read_csv("fallecidos.csv")
DFVacunadosRAW <- read_csv("vacunados.csv")
```

# Asignamos DF's limpias de N/A's y con variables renombradas
```{r}
DFVacunadosCLEAN<-subset(DFVacunadosRAW,select = -c(FECHA_CORTE,UUID,DIRESA,PROVINCIA,DISTRITO))
DFFallecidosCLEAN<-subset(DFFallecidosRAW,select = -c(FECHA_CORTE,UUID,FECHA_NAC,UBIGEO,PROVINCIA,DISTRITO))
DFFallecidosCLEAN %>% rename("EDAD"= "EDAD_DECLARADA")-> DFFallecidosCLEAN
DFVacunadosCLEAN %>% rename("GRUPO"="GRUPO_RIESGO")-> DFVacunadosCLEAN
```

# Revisamos el numero de observaciones incompletas
```{r}
#DFVacunadosRAW[which(!complete.cases(DFVacunadosRAW)),]
round(sum(!complete.cases(DFVacunadosRAW))/nrow(DFVacunadosRAW)*100,2)
```


# Copia para la grafica del objetivo 1 

```{r}
#DFFallecidosCopy<- DFFallecidosCLEAN$FECHA_FALLECIMIENTO
#DFDia <- toString(str_sub(DFFallecidosCopy,-2,-1)) #dia
#(DFFallecidosCopy,-4,-3) #mes
#str_sub(DFFallecidosCopy, end = 4) #anho
#hist(DFFallecidosCopy$FECHA_FALLECIMIENTO,breaks=100)
```


```{r}
#vector<-DFFallecidosCLEAN$FECHA_FALLECIMIENTO
#DFFallecidosCopy<-DFFallecidosCLEAN[,1]
#dia<-str_sub(vector,-2,-1) #dia
#mes<-str_sub(vector,-4,-3) #mes
#anio<-str_sub(vector, end = 4) #ano
#date = paste(anio,"-",mes,"-",dia, sep = "")
#DFFallecidosCopy$DATE <- as.Date(date)
#DFFallecidosCopy<-DFFallecidosCopy[,2]
#DFFallecidosCopy
#hist(DFFallecidosCopy$DATE,breaks=24)
```

```{r}
vector<-DFFallecidosCLEAN$FECHA_FALLECIMIENTO
DFFallecidosCopy<-DFFallecidosCLEAN[,1]
dia<-str_sub(vector,-2,-1) #dia
mes<-str_sub(vector,-4,-3) #mes
anio<-str_sub(vector, end = 4) #ano
date = paste(anio,"-",mes,"-",dia, sep = "")
DFFallecidosCopy$fecha <- lubridate::ymd(date)
DFFallecidosCopy<-DFFallecidosCopy[,2]
#DFFallecidosCopy
#DFFallecidosCopy %>% group_by(DFFallecidosCopy$fecha) %>% tally -> DFFallecidosCopy
#DFFallecidosCopy
```

```{r}
vector<-DFVacunadosCLEAN$FECHA_VACUNACION
DFVacunadosCopy<-DFVacunadosCLEAN[,1]
dia<-str_sub(vector,-2,-1) #dia
mes<-str_sub(vector,-4,-3) #mes
anio<-str_sub(vector, end = 4) #ano
date = paste(anio,"-",mes,"-",dia, sep = "")
DFVacunadosCopy$fecha <- lubridate::ymd(date)
DFVacunadosCopy<-DFVacunadosCopy[,2]
```



```{r}
DFFallecidosCopy %>% group_by(DFFallecidosCopy$DATE) %>% tally()
#hist(DFFallecidosCopy$DATE,breaks = 100, )
```

#
```{r}
by_month <- function(x,n=1){
  seq(min(x,na.rm=T),max(x,na.rm=T),by=paste0(n," months"))
}
ggplot(DFFallecidosCopy,aes(fecha )) +
  geom_histogram(breaks = by_month(DFFallecidosCopy$fecha)) +
  scale_x_date(labels = scales::date_format("%Y-%b"),
               breaks = by_month(DFFallecidosCopy$fecha,2)) + 
  theme(axis.text.x = element_text(angle=90))
```

#Boxplot Edad Fallecidos
```{r}
boxplot(DFFallecidosCLEAN$EDAD,horizontal = TRUE,col = "yellow")
abline(v=mean(DFFallecidosCLEAN$EDAD),col="red")
```
#Boxplot Edad Vacunados
```{r}
boxplot(DFVacunadosCLEAN$EDAD,horizontal = TRUE,col = "yellow")
abline(v=mean(DFVacunadosCLEAN$EDAD, na.rm = TRUE),col="red")

```

#Boxplot Fecha Vacunados
```{r}
boxplot(DFVacunadosCopy$FE,horizontal = TRUE,col = "green")
abline(v=mean(DFVacunadosCopy$fecha),col="blue")
```

#Gráfico de barras DOSIS VACUNADOS
```{r}
barplot(table(DFVacunadosCLEAN$DOSIS), col = "skyblue")
```
