---
author: "Mauricio Rodriguez, Renato Rodriguez, Sebastian Quispe, Christian Salazar, Frings Barrueta" 
title: "Impacto del proceso de vacunación contra la Covid-19"
date: "June 9th 2021"
output:
  html_document:
    toc: yes
    df_print: paged
  html_notebook:
    toc: yes
    toc_float:
      collapsed: no
      smooth_scroll: no
    number_sections: yes
    theme: journal
---
# Cargar librerias 
```{r}
library(readr)
library(dplyr)
library (ggplot2)
library(stringr)
library(scales)
library(lubridate)
library(modeest)
library(viridis)
``` 

# Asignar DF's con los datos RAW de los archivos
```{r}
DFFallecidosRAW <- read_csv("fallecidos.csv")
DFVacunadosRAW <- read_csv("vacunados.csv")
```

# Limpieza tabla DFFallecidos
```{r echo = FALSE}
DFFallecidosCLEAN<-subset(DFFallecidosRAW,select = -c(FECHA_CORTE,UUID,UBIGEO,PROVINCIA,DISTRITO))

DFFallecidosCLEAN %>% rename("EDAD"= "EDAD_DECLARADA")-> DFFallecidosCLEAN

vector<-DFFallecidosCLEAN$FECHA_FALLECIMIENTO
dia<-str_sub(vector,-2,-1) #dia
mes<-str_sub(vector,-4,-3) #mes
anio<-str_sub(vector, end = 4) #anio
date = paste(anio,"-",mes,"-",dia, sep = "")
DFFallecidosCLEAN$FECHA_FALLECIMIENTO<- lubridate::ymd(date)
DFFallecidosCLEAN<-filter(DFFallecidosCLEAN,SEXO != "INDETERMINADO")
```

# Limpieza tabla DFVacunados
```{r echo = FALSE}
DFVacunadosCLEAN<-subset(DFVacunadosRAW,select = -c(FECHA_CORTE,UUID,DIRESA,PROVINCIA,DISTRITO))
DFVacunadosCLEAN %>% rename("GRUPO"="GRUPO_RIESGO")-> DFVacunadosCLEAN

vector<-DFVacunadosCLEAN$FECHA_VACUNACION
dia<-str_sub(vector,-2,-1) #dia
mes<-str_sub(vector,-4,-3) #mes
anio<-str_sub(vector, end = 4) #anio
date = paste(anio,"-",mes,"-",dia, sep = "")
DFVacunadosCLEAN$FECHA_VACUNACION<- lubridate::ymd(date)
```


# Figuras de Mérito

## Dataset FALLECIDOS

### FECHA_FALLECIMIENTO
```{r, echo=FALSE}
DFFechaFallecidos <- as.data.frame(table(DFFallecidosCLEAN$FECHA_FALLECIMIENTO))
ggplot(data = DFFallecidosCLEAN, aes(FECHA_FALLECIMIENTO)) + 
  geom_freqpoly() + 
  scale_x_date(date_minor_breaks = "1 day", date_labels = "%b %d") +
  labs(title = "Polígono de dispersión de fallecidos por COVID-19",
       x = "Fecha",
       y = "Cantidad de fallecidos")
```

### EDAD
```{r, echo=FALSE}
ggplot(data = DFFallecidosCLEAN, aes(x=EDAD)) + 
  geom_histogram(aes(fill=..count..)) + 
  scale_fill_viridis("Frecuencia", discrete=F) + 
  labs(title="Edades de personas fallecidas por COVID-19",
       x="Edad(años)",
       y="Frecuencia")
```

### SEXO
```{r, echo=FALSE}
options(scipen=999)
barplot(table(DFFallecidosCLEAN$SEXO),
        main="Sexo de personas fallecidas por COVID-19",
        col=c("orange", "blue"),
        legend.text=c("Mujeres", "Hombres"),
        ylim = c(0,150000),
        ylab = "Frecuencia"
)
```

### DEPARTAMENTO
```{r, echo=FALSE}
ggplot(data = DFFallecidosCLEAN, aes(x=DEPARTAMENTO)) + 
  geom_histogram(aes(fill=..count..), stat = "count") + 
  scale_fill_viridis("Frecuencia", discrete=F) + 
  labs(title="Departamentos de fallecidos por COVID-19",
       x="Departamento",
       y="Frecuencia")
```

## Dataset PROCESO DE VACUNACIÓN

### FECHA_VACUNACION x EDAD
```{r}

```


### SEXO
```{r, echo=FALSE}
options(scipen=999)
barplot(table(DFVacunadosCLEAN$SEXO),
        main="Sexo de personas vacunadas por COVID-19",
        col=c("orange", "blue"),
        legend.text=c("Mujeres", "Hombres"),
        ylim = c(0,2000000),
        ylab = "Frecuencia"
)
```

### DOSIS
```{r, echo=FALSE}
ggplot(data = DFVacunadosCLEAN, aes(x=DOSIS)) + 
  geom_histogram(aes(fill=..count..), stat = "count") + 
  scale_fill_viridis("Frecuencia", discrete=F) + 
  labs(title="Dosis de vacunas por COVID-19",
       x="Dosis",
       y="Frecuencia")
```

### FABRICANTE
```{r, echo=FALSE}
ggplot(data = DFVacunadosCLEAN, aes(x=FABRICANTE)) + 
  geom_histogram(aes(fill=..count..), stat = "count") + 
  scale_fill_viridis("Frecuencia", discrete=F) + 
  labs(title="Fabricantes de vacunas por COVID-19",
       x="Fabricante",
       y="Frecuencia")
```

### DEPARTAMENTO
```{r, echo=FALSE}
ggplot(data = DFVacunadosCLEAN, aes(x=DEPARTAMENTO)) + 
  geom_histogram(aes(fill=..count..), stat = "count") + 
  scale_fill_viridis("Frecuencia", discrete=F) + 
  labs(title="Departamentos de vacunados por COVID-19",
       x="Departamento",
       y="Frecuencia")
```


